# Generated by Django 3.2.8 on 2021-10-31 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item_img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('item_description', models.CharField(max_length=400)),
                ('item_location', models.CharField(max_length=20)),
                ('item_remaining_time', models.DateTimeField()),
                ('ispection_start', models.DateTimeField()),
                ('ispection_end', models.DateTimeField()),
                ('min_increment', models.IntegerField()),
                ('attribute', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('item_date_added', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.category')),
            ],
            options={
                'ordering': ('item_date_added',),
            },
        ),
    ]
