# Generated by Django 3.2.8 on 2021-11-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bidder',
            fields=[
                ('bidder_id', models.AutoField(primary_key=True, serialize=False)),
                ('bidder_first_name', models.IntegerField(max_length=30)),
                ('bidder_last_name', models.CharField(max_length=30)),
                ('bidder_email', models.EmailField(max_length=30)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
    ]
